name: Villemorin
favicon: null
layout_spectrum: 0.7619918757118285
typography_spectrum: 0.46303
title: Villemorin France 2012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#21141b'
    - '#877c84'
    - '#00c3fe'
    - '#dc0001'
  brandStrength: 0.7241545321885496
  lightness: 0.6384558880236
  saturation: 0.4707302644383162
  rhythmicContrast: 0.6150500224903226
purpose: []
