name: Villemorin
favicon: null
layout_spectrum: 0.33453
typography_spectrum: 0.46303
title: Villemorin France 2012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#21141b'
    - '#877c84'
    - '#00c3fe'
    - '#dc0001'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.4707302644383162
  rhythmicContrast: 0.25
purpose: []
