name: Villemorin
favicon: null
layout_spectrum: 0.33453
typography_spectrum: 0.46303
title: Villemorin France 2012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#828fb2'
    - '#152d13'
    - '#856a43'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.4707302644383162
  rhythmicContrast: 0.25
purpose: []
